development:
  adapter: postgresql
  encoding: unicode
  database: tonyhawk_dev
  pool: 5
  username: kevin
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tonyhawk_test
  pool: 5
  username: kevin
  password:
